[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
client_lib = { path = "../client_lib" }
crossterm = "0.27.0"
tokio = { version = "1", features = ["full"] }
tui = "0.19.0"
